FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

COPY graphdb-*.tgz ./

RUN ls -la

RUN npm install

RUN PACKAGE=$(find . -name "graphdb-*.tgz") && npm install $PACKAGE

COPY . .

CMD ["npm", "run", "test"]
